# Metodo de la potencia

In [43]:
import numpy as np

def power_method(A, tol=1e-6, max_iter=6):
    n, m = A.shape
    b = np.array([1, 0])
    b = b / np.linalg.norm(b)
    
    for _ in range(max_iter):
        b_old = b.copy()
        b = np.dot(A, b)
        
        b = b / np.linalg.norm(b)
        
        print(f"b: {b}")
        
        if np.linalg.norm(b - b_old) < tol:
            break
    
    lambda_ = np.dot(b.T, np.dot(A, b))
    return lambda_, b

# Ejemplo de uso
A = np.array([[3, 1], [2, 2]])
lambda_, b = power_method(A)
print(f"Autovalor dominante: {lambda_}")
print(f"Autovector correspondiente: {b}")


b: [0.83205029 0.5547002 ]
b: [0.73994007 0.67267279]
b: [0.71537618 0.69873952]
b: [0.70917736 0.70503012]
b: [0.70762462 0.70658856]
b: [0.70723625 0.70697729]
Autovalor dominante: 4.000183016044049
Autovector correspondiente: [0.70723625 0.70697729]


# Metodo de la potencia escalonada

In [54]:
import numpy as np

def power_method_with_scaling(A, tol=1e-5, max_iter=1000):
    n, m = A.shape
    x = np.array([1,1,0])
    x = np.dot(A, x)
    x_max = np.max(np.abs(x))
    
    x = x / x_max
    x_before = x_max
    print(f"Iteración {0}: mu = {x_max}, b = {x}")
    
    for k in range(max_iter):
        
        x = np.dot(A, x)
        x_max = np.max(np.abs(x))
        
        x = x / x_max
        
                
        if (x_max - x_before) < tol:
            break
    
        x_before = x_max      
        print(f"Iteración {k+1}: mu = {x_max}, b = {x}")
    
    return x_max, x

# Ejemplo de uso
A = np.array([[2, 0, 2], [-1, 2, 1], [0, 1, 4]])
lambda_, b = power_method_with_scaling(A)
print(f"Autovalor dominante: {lambda_}")
print(f"Autovector correspondiente: {b}")


Iteración 0: mu = 2, b = [1.  0.5 0.5]
Iteración 1: mu = 3.0, b = [1.         0.16666667 0.83333333]
Iteración 2: mu = 3.666666666666667, b = [1.         0.04545455 0.95454545]
Iteración 3: mu = 3.909090909090909, b = [1.         0.01162791 0.98837209]
Iteración 4: mu = 3.9767441860465116, b = [1.         0.00292398 0.99707602]
Iteración 5: mu = 3.9941520467836256, b = [1.00000000e+00 7.32064422e-04 9.99267936e-01]
Iteración 6: mu = 3.998535871156662, b = [1.00000000e+00 1.83083120e-04 9.99816917e-01]
Iteración 7: mu = 3.999633833760527, b = [1.00000000e+00 4.57749702e-05 9.99954225e-01]
Iteración 8: mu = 3.9999084500595075, b = [1.00000000e+00 1.14440045e-05 9.99988556e-01]
Iteración 9: mu = 3.9999771119910275, b = [1.00000000e+00 2.86101749e-06 9.99997139e-01]
Iteración 10: mu = 3.9999942779650155, b = [1.00000000e+00 7.15255396e-07 9.99999285e-01]
Autovalor dominante: 3.9999985694892075
Autovector correspondiente: [1.00000000e+00 1.78813913e-07 9.99999821e-01]


# Metodo de la potencia inversa

In [62]:
def inverse_power_method(A, tol=1e-6, max_iter=1000):
    n, m = A.shape
    b = np.random.rand(n)
    b = b / np.linalg.norm(b)
    
    for _ in range(max_iter):
        b_old = b.copy()
        b = np.linalg.solve(A, b)
        b = b / np.linalg.norm(b)
        
        if np.linalg.norm(b - b_old) < tol:
            break
    
    lambda_ = np.dot(b.T, np.dot(A, b))
    return lambda_, b


A = np.array([[1, 2, 3], [2, 2, 3], [3, 3, 3]])


# Ejemplo de uso
lambda_, b = inverse_power_method(A)
print(f"Autovalor más pequeño: {lambda_}")
print(f"Autovector correspondiente: {b}")


Autovalor más pequeño: -0.33892170647767145
Autovector correspondiente: [-0.42509024  0.82915294 -0.36304778]


# Metodo de la potencia con desplazamiento

In [67]:
def shifted_power_method(A, mu, tol=1e-6, max_iter=1000):
    n, m = A.shape
    I = np.eye(n)
    b = np.random.rand(n)
    b = b / np.linalg.norm(b)
    
    for _ in range(max_iter):
        b_old = b.copy()
        b = np.linalg.solve(A - mu * I, b)
        b = b / np.linalg.norm(b)
        
        if np.linalg.norm(b - b_old) < tol:
            break
    
    lambda_ = np.dot(b.T, np.dot(A, b))
    return lambda_, b

A = np.array([[1, 2, 3], [2, 2, 3], [3, 3, 3]])


# Ejemplo de uso
mu = 5
lambda_, b = shifted_power_method(A, mu)
print(f"Autovalor cercano a {mu}: {lambda_}")
print(f"Autovector correspondiente: {b}")


Autovalor cercano a 5: 7.516538485191353
Autovector correspondiente: [0.48273956 0.5469629  0.68395475]


# QR Francis

In [59]:
import numpy as np

def qr_algorithm(A, tol=1e-5, max_iter=1000):
    n, m = A.shape
    Ak = A.copy()
    
    for i in range(max_iter):
        Q, R = np.linalg.qr(Ak)
        Ak = np.dot(R, Q)
        
        print(f"A{i}: ")
        print(Ak)
        
        if np.allclose(Ak, np.triu(Ak), atol=tol):
            break
    
    return np.diag(Ak)

A = np.array([[1, 2, 3], [2, 2, 3], [3, 3, 3]])

# Ejemplo de uso
eigenvalues = qr_algorithm(A)
print(f"Autovalores: {eigenvalues}")


A0: 
[[ 7.         -1.94145069  0.66712438]
 [-1.94145069 -0.53846154  0.18502701]
 [ 0.66712438  0.18502701 -0.46153846]]
A1: 
[[ 7.5033557   0.33650203  0.03441879]
 [ 0.33650203 -1.1474235  -0.11736312]
 [ 0.03441879 -0.11736312 -0.3559322 ]]
A2: 
[[ 7.51621499e+00 -5.30082384e-02  1.56785729e-03]
 [-5.30082384e-02 -1.17584809e+00  3.47787828e-02]
 [ 1.56785729e-03  3.47787828e-02 -3.40366900e-01]]
A3: 
[[ 7.51653055e+00  8.30789298e-03  7.07521151e-05]
 [ 8.30789298e-03 -1.17748892e+00 -1.00277931e-02]
 [ 7.07521151e-05 -1.00277931e-02 -3.39041621e-01]]
A4: 
[[ 7.51653829e+00 -1.30163574e-03  3.19043277e-06]
 [-1.30163574e-03 -1.17760665e+00  2.88642570e-03]
 [ 3.19043277e-06  2.88642570e-03 -3.38931640e-01]]
A5: 
[[ 7.51653848e+00  2.03927866e-04  1.43857816e-07]
 [ 2.03927866e-04 -1.17761595e+00 -8.30731283e-04]
 [ 1.43857815e-07 -8.30731283e-04 -3.38922529e-01]]
A6: 
[[ 7.51653849e+00 -3.19494037e-05  6.48657027e-09]
 [-3.19494037e-05 -1.17761671e+00  2.39087217e-04]
 [ 6.486570