# HouseHolder QR

In [20]:
import numpy as np
A = np.array([[2, 2, 0], [0, 4, 0], [0, -3, 5]], dtype=float)
H = np.array([[1, 0,0],[0,0.8,-0.6],[0,0.6,0.8]])

H@A

array([[ 2.00000000e+00,  2.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  5.00000000e+00, -3.00000000e+00],
       [ 0.00000000e+00, -2.22044605e-16,  4.00000000e+00]])

In [17]:
import numpy as np

def householder_reflection(a):
    """
    Computes the Householder reflection matrix for vector a.
    """
    v = a.copy()
    v[0] += np.sign(a[0]) * np.linalg.norm(a)
    print(f"v = {v}")
    v = v / np.linalg.norm(v)
    H = np.eye(len(a)) - 2 * np.outer(v, v)
    return H

def qr_decomposition(A):
    """
    Computes the QR decomposition of matrix A using Householder reflections.
    """
    m, n = A.shape
    R = A.copy()
    Q = np.eye(m)

    for i in range(n):
        # Extract the vector to be reflected
        x = R[i:, i]
        # Compute the Householder reflection matrix
        H_i = np.eye(m)
        H_i[i:, i:] = householder_reflection(x)
        # Apply the Householder reflection
        R = H_i @ R
        Q = Q @ H_i.T
        print(f"Matriz R{i+1}:")
        print(R)
        print(f"Matriz H{i+1}:")
        print(H_i)
        
        
    return Q, R

# Ejemplo de uso
A = np.array([[1, -4], [2, 3], [2, 2]], dtype=float)
Q, R = qr_decomposition(A)

print("Matriz Q:")
print(Q)
print("Matriz R:")
print(R)

v = [4. 2. 2.]
Matriz R1:
[[-3.00000000e+00 -2.00000000e+00]
 [-6.66133815e-16  4.00000000e+00]
 [-6.66133815e-16  3.00000000e+00]]
Matriz H1:
[[-0.33333333 -0.66666667 -0.66666667]
 [-0.66666667  0.66666667 -0.33333333]
 [-0.66666667 -0.33333333  0.66666667]]
v = [9. 3.]
Matriz R2:
[[-3.00000000e+00 -2.00000000e+00]
 [ 9.32587341e-16 -5.00000000e+00]
 [-1.33226763e-16  2.22044605e-16]]
Matriz H2:
[[ 1.   0.   0. ]
 [ 0.  -0.8 -0.6]
 [ 0.  -0.6  0.8]]
Matriz Q:
[[-0.33333333  0.93333333 -0.13333333]
 [-0.66666667 -0.33333333 -0.66666667]
 [-0.66666667 -0.13333333  0.73333333]]
Matriz R:
[[-3.00000000e+00 -2.00000000e+00]
 [ 9.32587341e-16 -5.00000000e+00]
 [-1.33226763e-16  2.22044605e-16]]


# Givens QR

In [18]:
import numpy as np

def givens_rotation(a, b):
    """
    Computes the Givens rotation matrix elements c and s
    such that applying the rotation to [a, b] results in [r, 0].
    """
    if b == 0:
        c = 1
        s = 0
    else:
        if np.abs(b) > np.abs(a):
            tau = -a / b
            s = 1 / np.sqrt(1 + tau**2)
            c = s * tau
        else:
            tau = -b / a
            c = 1 / np.sqrt(1 + tau**2)
            s = c * tau
    return c, s

def qr_decomposition_givens(A):
    """
    Computes the QR decomposition of matrix A using Givens rotations.
    """
    m, n = A.shape
    Q = np.eye(m)
    R = A.copy()

    for j in range(n):
        for i in range(m-1, j, -1):
            G = np.eye(m)
            c, s = givens_rotation(R[i-1, j], R[i, j])
            G[[i-1, i], [i-1, i]] = c
            G[i, i-1] = s
            G[i-1, i] = -s
            R = G @ R
            Q = Q @ G.T
            print(f"Matriz G{i+1}{j+1}:")
            print(G)

    return Q, R

# Ejemplo de uso
A = np.array([[2, 2, 0], [0, 4, 0], [0, -3, 5]], dtype=float)
Q, R = qr_decomposition_givens(A)

print("Matriz Q:")
print(Q)
print("Matriz R:")
print(R)

Matriz G31:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Matriz G21:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Matriz G32:
[[ 1.   0.   0. ]
 [ 0.   0.8 -0.6]
 [ 0.   0.6  0.8]]
Matriz Q:
[[ 1.   0.   0. ]
 [ 0.   0.8  0.6]
 [ 0.  -0.6  0.8]]
Matriz R:
[[ 2.00000000e+00  2.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  5.00000000e+00 -3.00000000e+00]
 [ 0.00000000e+00  2.22044605e-16  4.00000000e+00]]


In [4]:
import numpy as np

A = np.array([[1, 1, 1], [1, 1, 2], [1, 2, 1], [1, 2, 2], [1, 2, 3]])
An = A.T@A

b = np.array([7, 9, 10, 11, 12])
bn = A.T@b

x = backward_substitution(An, b)

# Inversa de una matriz



IndexError: index 4 is out of bounds for axis 0 with size 3

In [7]:
# solucion regresiva 
import numpy as np
def backward_substitution(A, b):
    """
    Solves the upper triangular system Ax = b using backward substitution.
    """
    n = len(b)
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = (b[i] - np.dot(A[i, i+1:], x[i+1:])) / A[i, i]
    return x



A = np.array([[1, 1, 1], [1, 1, 2], [1, 2, 1], [1, 2, 2], [1, 2, 3]])
An = A.T@A

b = np.array([7, 9, 10, 11, 12])
bn = A.T@b

x = backward_substitution(An, bn)
print(x)









[0.00902256 0.61278195 4.89473684]


In [8]:
An

array([[ 5,  8,  9],
       [ 8, 14, 15],
       [ 9, 15, 19]])

In [9]:
bn

array([49, 82, 93])

In [5]:
# graficar el plano obtenido con los valores x con matplotlib




IndexError: index 4 is out of bounds for axis 0 with size 3