# HouseHolder QR

In [18]:
import numpy as np

def householder_reflection(a):
    """
    Computes the Householder reflection matrix for vector a.
    """
    v = a.copy()
    v[0] += np.sign(a[0]) * np.linalg.norm(a)
    v = v / np.linalg.norm(v)
    H = np.eye(len(a)) - 2 * np.outer(v, v)
    return H

def qr_decomposition(A):
    """
    Computes the QR decomposition of matrix A using Householder reflections.
    """
    m, n = A.shape
    R = A.copy()
    Q = np.eye(m)

    for i in range(n):
        # Extract the vector to be reflected
        x = R[i:, i]
        # Compute the Householder reflection matrix
        H_i = np.eye(m)
        H_i[i:, i:] = householder_reflection(x)
        # Apply the Householder reflection
        R = H_i @ R
        Q = Q @ H_i.T
        print(f"Matriz H{i+1}:")
        print(H_i)

    return Q, R

# Ejemplo de uso
A = np.array([[1, 1, 1], [12, 10, 9], [2, -1, 0]], dtype=float)
Q, R = qr_decomposition(A)

print("Matriz Q:")
print(Q)
print("Matriz R:")
print(R)

Matriz H1:
[[-0.08192319 -0.9830783  -0.16384638]
 [-0.9830783   0.10673608 -0.14887732]
 [-0.16384638 -0.14887732  0.97518711]]
Matriz H2:
[[ 1.          0.          0.        ]
 [ 0.         -0.0883807   0.99608677]
 [ 0.          0.99608677  0.0883807 ]]
Matriz H3:
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0. -1.]]
Matriz Q:
[[-0.08192319 -0.07632007  0.99371215]
 [-0.9830783  -0.15772814 -0.09316051]
 [-0.16384638  0.98452886  0.06210701]]
Matriz R:
[[-1.22065556e+01 -9.74885985e+00 -8.92962793e+00]
 [-8.34039447e-17 -2.63813031e+00 -1.49587331e+00]
 [-9.39996696e-16 -4.20874975e-16  1.55267524e-01]]


# Givens QR

In [22]:
import numpy as np

def givens_rotation(a, b):
    """
    Computes the Givens rotation matrix elements c and s
    such that applying the rotation to [a, b] results in [r, 0].
    """
    if b == 0:
        c = 1
        s = 0
    else:
        if np.abs(b) > np.abs(a):
            tau = -a / b
            s = 1 / np.sqrt(1 + tau**2)
            c = s * tau
        else:
            tau = -b / a
            c = 1 / np.sqrt(1 + tau**2)
            s = c * tau
    return c, s

def qr_decomposition_givens(A):
    """
    Computes the QR decomposition of matrix A using Givens rotations.
    """
    m, n = A.shape
    Q = np.eye(m)
    R = A.copy()

    for j in range(n):
        for i in range(m-1, j, -1):
            G = np.eye(m)
            c, s = givens_rotation(R[i-1, j], R[i, j])
            G[[i-1, i], [i-1, i]] = c
            G[i, i-1] = s
            G[i-1, i] = -s
            R = G @ R
            Q = Q @ G.T
            print(f"Matriz G{i+1}{j+1}:")
            print(G)

    return Q, R

# Ejemplo de uso
A = np.array([[1, 1, 1], [12, 10, 9], [2, -1, 0]], dtype=float)
Q, R = qr_decomposition_givens(A)

print("Matriz Q:")
print(Q)
print("Matriz R:")
print(R)

Matriz G31:
[[ 1.          0.          0.        ]
 [ 0.          0.98639392  0.16439899]
 [ 0.         -0.16439899  0.98639392]]
Matriz G21:
[[-0.08192319 -0.99663865  0.        ]
 [ 0.99663865 -0.08192319  0.        ]
 [ 0.          0.          1.        ]]
Matriz G32:
[[ 1.          0.          0.        ]
 [ 0.          0.07657747 -0.99706363]
 [ 0.          0.99706363  0.07657747]]
Matriz Q:
[[-0.08192319  0.07632007  0.99371215]
 [-0.9830783   0.15772814 -0.09316051]
 [-0.16384638 -0.98452886  0.06210701]]
Matriz R:
[[-1.22065556e+01 -9.74885985e+00 -8.92962793e+00]
 [-2.16366880e-16  2.63813031e+00  1.49587331e+00]
 [ 8.24401407e-17 -3.35563857e-17  1.55267524e-01]]


In [23]:
# solucion regresiva 

def backward_substitution(A, b):
    """
    Solves the upper triangular system Ax = b using backward substitution.
    """
    n = len(b)
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = (b[i] - np.dot(A[i, i+1:], x[i+1:])) / A[i, i]
    return x


# Ejemplo de uso
A = np.array([[1, 2, 3], [0, 5, 6], [0, 0, 9]], dtype=float)
b = np.array([1, 2, 3], dtype=float)
x = backward_substitution(A, b)

print(x)

[0.         0.         0.33333333]
